# 两条链的 RPC 地址和私钥
deploy_L1:
    forge script script/mintNFT.s.sol --broadcast --rpc-url $(RPC1) --private-key $(PRIVATE_KEY)
deploy_L2:
    forge script script/mintNFT.s.sol --broadcast --rpc-url $(RPC2) --private-key $(PRIVATE_KEY)